---
# Needs to be more smart about which ssh key to use. currently hardcoded to use id_rsa
# Also currently broken
# - include_tasks: github_ssh_user.yml
- name: Checkout password-store
  git: 
    accept_hostkey: yes
    clone: yes
    dest: "{{ desktop_user_vars.dir }}/.password-store"
    repo: "{{ pass_git_uri }}"
    recursive: yes
    update: no
  when:
    - skip_local_server is not defined
    - limited_internet is not defined
- name: setup go config dir
  file:
    state: directory
    path: "{{ desktop_user_vars.dir }}/.config/go"
- name: configure go
  template:
    src: goenv
    dest: "{{ desktop_user_vars.dir }}/.config/go/env"
- name: install go modules
  command: >
    go install {{ item }}
  environment:
    GOPATH: "{{ desktop_user_vars.dir }}/Source/go"
  with_items: "{{ go_default_binaries + go_binaries }}"
- include_tasks: amtool_config.yml
  when: amtool_config is defined
