---
# Needs to be more smart about which ssh key to use. currently hardcoded to use id_rsa
# Also currently broken
# - include_tasks: github_ssh_user.yml
- name: Checkout password-store
  git: 
    accept_hostkey: yes
    clone: yes
    dest: "{{ desktop_user_vars.dir }}/.password-store"
    repo: "{{ pass_git_uri }}"
    recursive: no
    update: no
  when:
    - skip_local_server is not defined
    - limited_internet is not defined
- name: install go modules
  command: >
    go install {{ item }}
  environment:
    GOPATH: "{{ desktop_user_vars.dir }}/Source/go"
  with_items:
  - github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
  - golang.org/x/tools/cmd/goimports@latest
  - github.com/bazelbuild/buildtools/buildifier@latest
  - github.com/prometheus/alertmanager/cmd/amtool@latest
  - github.com/bazelbuild/bazelisk@latest
  - github.com/homeport/dyff/cmd/dyff@latest
  - github.com/mikefarah/yq/v4@latest
- include_tasks: amtool_config.yml
  when: amtool_config is defined
