---
# Needs to be more smart about which ssh key to use. currently hardcoded to use id_rsa
- include_tasks: github_ssh_user.yml
- name: Checkout password-store
  git: 
    accept_hostkey: yes
    clone: yes
    dest: "{{ desktop_user_vars.dir }}/.password-store"
    repo: "{{ pass_git_uri }}"
    recursive: no
  when:
    - skip_local_server is not defined
    - limited_internet is not defined
